// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_bFsiRz6pxShLJemgJ_2otgvq7_mfPwI',
    appId: '1:658826686427:web:c75962dd1515d569d601fe',
    messagingSenderId: '658826686427',
    projectId: 'gemini-dd161',
    authDomain: 'gemini-dd161.firebaseapp.com',
    storageBucket: 'gemini-dd161.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsD7T8-uCMiv5GHmSZ9P_Om6Ci6wtVL0o',
    appId: '1:658826686427:android:11d19ab49689efb5d601fe',
    messagingSenderId: '658826686427',
    projectId: 'gemini-dd161',
    storageBucket: 'gemini-dd161.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClwM7JSN-AdTTeNY2KMfD8c4MiADggCXc',
    appId: '1:658826686427:ios:5eb0d24429a4ce42d601fe',
    messagingSenderId: '658826686427',
    projectId: 'gemini-dd161',
    storageBucket: 'gemini-dd161.firebasestorage.app',
    iosBundleId: 'com.example.colorfulLoginGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClwM7JSN-AdTTeNY2KMfD8c4MiADggCXc',
    appId: '1:658826686427:ios:fd21d2df757584a1d601fe',
    messagingSenderId: '658826686427',
    projectId: 'gemini-dd161',
    storageBucket: 'gemini-dd161.firebasestorage.app',
    iosBundleId: 'n',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_bFsiRz6pxShLJemgJ_2otgvq7_mfPwI',
    appId: '1:658826686427:web:519bb339349857ddd601fe',
    messagingSenderId: '658826686427',
    projectId: 'gemini-dd161',
    authDomain: 'gemini-dd161.firebaseapp.com',
    storageBucket: 'gemini-dd161.firebasestorage.app',
  );
}
